### ISSUE TITLE
Help with get.xloc.sh and update_reference.sh scripts

### ISSUE THREAD

**Issue by jorels** [wurmlab/genomicscourse#22]
Hi,

I do hope this meets you well.

I have been running an RNA-Seq analysis on a non-model organism and I stumbled upon your tutorial on Differential Gene Expression. The subsection on Renaming our favorite candidate genes (so we can find them easily) fits perfectly for what I intend to achieve with my analysis. Unfortunately, I am unable to proceed beyond the blastx on the merged.fa data. 

I was wondering if you could please grant me access to the scripts "get.xloc.sh and update_reference.sh" so that I may complete that aspect of my analysis. I would be very grateful if you could help me with this.

Many thanks,

Joachim

**Comment by yannickwurm** [comment]
Dear Joachim,

thank you for the message - I am happy that this is useful. I think you're referring to the bit that Oksana Riba helped to prepare - so thanks go do her as well.

The "recipes" we provided here are part of a course that we developed - a *very* dumbed down version of a real analysis that serves to demonstrate how one type of analysis can be done. It was specifically simplified so that it would - for example - run within the few numbers of hours that we had on the course, on laptops in 2012, in the middle of the alps without reliable internet access. 

The steps we performed should thus *not* be considered "the best way" of doing things. They were simply a tool to demonstrate the concepts of new analyses the students had not yet been exposed to. I would not trust those steps for any real analysis. Furthermore, a real dataset likely has idiosyncrasies that differ from those that our example dataset did. 

The specific files you are requesting in fact perform quite basic bioinformatics tasks. I no longer have access to them but it shouldn't matter. You would want to be able to do that type of manipulation yourself (without an example) before applying the approach to a bigger dataset. If you cannot trust your ability to understand what is going on - you probably should not trust any of the results either. (and you should ensure that your supervisor understands the risks you/they are taking). 

Kind regards and all the best,

Yannick
