### ISSUE TITLE
2019 - quality control of genes

### ISSUE THREAD

**Issue by yeban** [wurmlab/genomicscourse#24]
"Quality control of individual genes" section in gene prediction practical asks students to run BLAST on Apocrita and inspect the results on local PC. We want to simplify this if possible:

Test that BLAST can be run in a reasonable time on the local PC (which seems well equipped - 4 HT cores, 16 GB RAM).
- Test this through locally installed seqserv rather than on CLI. Make sure to start sequenceserver with `-n 8` and this should be reflected in the practical too (or ask Tom and team to change ~/.sequenceserver.conf for both `database_dir` and `num_threads` param).

If cannot run BLAST on local PC, ideal would be to run BLAST on Apocrita and visualise results on local PC using sequenceserver 2.0 beta:
- Test that 2.0 beta won't struggle to render the results. If it won't, update practical accordingly. If it will, update practicals to ask them to run BLAST with `-html` flag (we asked them to figure this out themselves last time, but might be tough with 50 students?).

Update or ask (Tom King) to update the copy of uniref50 in `/import/teaching/bio/data` (or the relevant copy on Apocrita if we determine that BLAST cannot be run on local PC)?

**Comment by yeban** [comment]
BLASTP 100 queries against uniref50 using 8 threads takes about 8 minutes.

**Comment by yannickwurm** [comment]
We want to run this locally - chaos to use apocrita, and also indeed chaos to read the CLI output.
       (a workaround may be  to use the commandline XML-loading (!)).

Tell them to take only the first X (10 if relevant?) genes? Similarly restricting the number of hits to 20 can greatly accelerate.
Or potentially phylogentic restriction

Yannick


On 23 Aug 2019, at 15:56, Anurag Priyam <notifications@github.com<mailto:notifications@github.com>> wrote:


"Quality control of individual genes" section in gene prediction practical asks students to run BLAST on Apocrita and inspect the results on local PC. We want to simplify this if possible:

Test that BLAST can be run in a reasonable time on the local PC (which seems well equipped - 4 HT cores, 16 GB RAM).

  *   Test this through locally installed seqserv rather than on CLI. Make sure to start sequenceserver with -n 8 and this should be reflected in the practical too (or ask Tom and team to change ~/.sequenceserver.conf for both database_dir and num_threads param).

Update or ask (Tom King) to update the copy of uniref50 in /import/teaching/bio/data (or the relevant copy on Apocrita if we determine that BLAST cannot be run on local PC)?

**Comment by yeban** [comment]
This is done. The conclusion is that students will run BLAST on local PC using sequenceserver 2.0 beta. Expected time to BLAST 2-7 queries is ~3 mins. The practical has been updated.
