### ISSUE TITLE
Per-tile graph doesn't appear in FASTQC report

### ISSUE THREAD

**Issue by yeban** [wurmlab/genomicscourse#66]
This is because the FASTQ sequence headers are not valid.

Thanks to Guy for reporting the issue.

**Comment by yannickwurm** [comment]
Might there be an effect of fastqc version?

I am certain that it has appeared in the HTML report or the Java app.

On 2020Aug7, at 18:04, Anurag Priyam <notifications@github.com<mailto:notifications@github.com>> wrote:



This is because the FASTQ sequence headers are not valid.

Thanks to Guy for reporting the issue.
